services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stims-db
    image: stims-db:latest
    restart: always
    environment:
      POSTGRES_USER: stims_admin
      POSTGRES_PASSWORD:
    volumes:
      - stims-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  stims-db:
    name: stims-db
