services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: stims-db:latest
    container_name: stims-db
    volumes:
      - stims-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE:
      MARIADB_ROOT_PASSWORD:
      MARIADB_USER:
      MARIADB_PASSWORD:
    ports:
      - "3306:3306"
volumes:
  stims-db:
    name: stims-db
